architecture_config:
  num_classes: 10

dataset_config:
  train_size: 40000
  val_size: 10000
  test_size: 10000
  img_size: 32

training_config:
  model_type: resnet
  per_replica_batch_size: 128
  local_steps: 100
  num_epochs: 2

inner_optimizer_config:
  lr: 1e-3
  weight_decay: 0.1
  b1: 0.9
  b2: 0.999

outer_optimizer_config:
  lr: 0.7
  momentum: 0.9
  nesterov: true

scheduler_config:
  num_warmup_steps: 0
  num_training_steps: 200